### ISSUE TITLE
Question about the Inference Results

### ISSUE THREAD

**Issue by Sanzo00** [TemporaryLoRA/Block-Attention#1]
Hello, BlockAttention Team, thank you for your excellent work! I encountered some issues while trying to reproduce the BlockAttention experiments and would appreciate your help.

I used the LLama-3-8b model and performed fine-tuning on a small subset of data (only 200 examples). When running `block_generate.py` for inference, the model’s output did not meet expectations, and it seemed unable to generate the correct answers. Here are some examples of the inference results:

```bash
# example1
Generated:
assistantassistantassistantassistantassistantassistantassistantassistantassistantassistantassistantassistantassistantassistantassistantassistant

# example2
Generated:
assistant assistant assistant assistant assistant assistant assistant assistant assistant assistant assistant assistant assistant assistant assistant assistant assistant assistant assistant assistant

# example3
Generated:
Title: Title: Title: Title: Title: Title: Title: Title: Title: Title: Title: Title: Title: Title: Title: Title: Title: Title: Title: Title: Title: Title: Title: Title: Title: Title
```

The output mainly consists of repetitive text. I am not sure if this is due to limitations in the LLama-3-8b model’s ability to understand user intent (would using an instruction-tuning version help?) or the limited amount of training data. I would greatly appreciate any insights or suggestions to help resolve this issue.

Thank you for your time, and I look forward to your response!

**Comment by libertywing** [comment]
Hi I think you may try Llama3-8B-Instruct. Since you only have 200 training samples, it is difficult to train the model to adapt to the task as well as to train it to adapt to the new attention mechanism. In addition, please be sure the last block should use self-attention so that it can attend the global.

**Comment by Sanzo00** [comment]
Thank you for your response and suggestions. I tried the Llama3-8B-Instruct model and also increased the dataset size. These adjustments significantly improved the results, and I am now able to achieve the expected outputs.  

Once again, thank you for your excellent work and support!
